modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "itensmod"
version = "${mod_version}"
displayName = "ItensMod — Itens Lendários"
logoFile = "itensmod:textures/item/legendary_lantern.png"
authors = "Dev-MatheusFelipe"
description = '''${mod_description}'''

# Dependência do Forge
[[dependencies.itensmod]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

# Dependência do Minecraft
[[dependencies.itensmod]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
